# Criando meu primeiro docker compose
networks:
  rede-app:
    name: rede-app
    driver: bridge

volumes:
  db-app:

services:

  http:
    container_name: http
    image: nginx:stable-alpine3.19-perl
    ports:
      - "8080:80"
    networks:
      - rede-app

  front-end:
    container_name: front-end
    build:
      context: ./front-end/
      dockerfile: Dockerfile.dev
      target: dev
    volumes:
      - ./front-end:/app
    ports:
      - "3000:3000"
    networks:
      - rede-app

  back-end:
    container_name: back-end
    build:
      context: ./back-end/
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./back-end:/app
    ports:
      - "3001:3000"
    networks:
      - rede-app

  db:
    container_name: db
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - db-app:/var/lib/postgresql/data
    networks:
      - rede-app

  db-adminer:
    container_name: db_adminer
    image: adminer:4.8.1
    ports:
      - 8081:8080
    networks:
      - rede-app

  cache:
    container_name: cache
    image: redis:7.2.4-alpine3.19
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - rede-app

  messaging:
    container_name: messaging
    image: apache/kafka:3.7.0
    networks:
    - rede-app
    ports:
    - 9092:9092
