# Criando meu primeiro docker compose
services:

  http:
    container_name: http
    image: nginx:stable-alpine3.19-perl
    ports:
      - "8080:80"

  front-end:
    container_name: front-end
    build:
      context: ./front-end/
      dockerfile: Dockerfile.dev
      target: dev
    volumes:
      - ./front-end:/app
    ports:
      - "3000:3000"

  back-end:
    container_name: back-end
    build:
      context: ./back-end/
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./back-end:/app
    ports:
      - "3001:3000"

  #db

  #cashe

  #messaging

