# Criando meu primeiro docker compose
volumes:
  db-app:

services:

  http:
    container_name: http
    image: nginx:stable-alpine3.19-perl
    ports:
      - "8080:80"

  front-end:
    container_name: front-end
    build:
      context: ./front-end/
      dockerfile: Dockerfile.dev
      target: dev
    volumes:
      - ./front-end:/app
    ports:
      - "3000:3000"

  back-end:
    container_name: back-end
    build:
      context: ./back-end/
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./back-end:/app
    ports:
      - "3001:3000"

  db:
    container_name: db
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - db-app:/var/lib/postgresql/data

  db-adminer:
    container_name: db_adminer
    image: adminer:4.8.1
    ports:
      - 8081:8080

  #cashe

  #messaging

